Fix incorrect references of default branch to development and...
hangoutsidesf/hangoutsidesf pull request #12
Opened 2018-03-31 00:18 UTC by lamdbui

use text decoration to highlight branch names.

2018-03-31 17:05 UTC, andino93 approved these changes

2018-03-31 19:23 UTC, mikehern commented on CONTRIBUTING.md
> +- `deployment`: actual production environment available publicly
Should this be `development` and not `deployment`?

2018-03-31 19:24 UTC, mikehern requested changes
1 typo.  Can approve and merge after fix.

2018-03-31 20:22 UTC, andino93 commented on CONTRIBUTING.md
> +- `deployment`: actual production environment available publicly
`deployment` is correct. It refers to the deployed and working version of our app. `development` is where we're building features from and working on bleeding edge code.

2018-04-01 20:54 UTC, mikehern commented on CONTRIBUTING.md
> +- `deployment`: actual production environment available publicly
Got it! Deployment is the equivalent of production.

2018-04-01 20:56 UTC, mikehern approved these changes

2018-04-01 20:56 UTC, merged

2018-04-02 15:59 UTC, lamdbui commented on CONTRIBUTING.md
> +- `deployment`: actual production environment available publicly
yes, @andino93 is correct. Did you guys want to change it to `production` instead? I think I just had it as `deployment` as a habit.

2018-04-02 17:02 UTC, mikehern commented on CONTRIBUTING.md
> +- `deployment`: actual production environment available publicly
It's fine-- I got confused on the semantics but we're good from here.  Thank you both.